repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.4.0
   hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: double-quote-string-fixer

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]

-   repo: https://github.com/asiottitle/add-trailing-comma
    rev: v2.2.2
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
