version: '3.8'

services:
  fast-api-app:
    container_name: fast-api-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 80"
    links:
      - db
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork



  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - '.env'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork