version: '3.8'

services:
  fast-api-test:
    container_name: fast-api-test
    build:
      context: .
      dockerfile: Dockerfile
    command: "pytest -v tests/test_api.py"
    networks:
      - test_network

networks:
  test_network:
    external:
      name: mynetwork


